export interface SecondaryStat {
  value: string
  label: string
}

export type PanelVariant = 'ink' | 'moss' | 'peach'

export interface CaseStudy {
  slug: string
  index: string
  company: string
  period: string
  /** Headline split so the emphasised clause can be rendered in the serif accent */
  titleLead: string
  titleEm: string
  description: string
  tags: string[]
  /** Metrics panel (right side of the card) */
  panelVariant: PanelVariant
  panelLabel: string
  dominant: string
  dominantEm: string
  dominantCaption: string
  secondary: [SecondaryStat, SecondaryStat]
}

export const caseStudies: CaseStudy[] = [
  {
    slug: 'lloyds-banking-group',
    index: '01',
    company: 'Lloyds Banking Group',
    period: '2023–present',
    titleLead: "Building the bank's",
    titleEm: 'AI-enabled lending platform.',
    description:
      "I own a key strategic outcome for Lloyds' Commercial Lending Platform, leading a cross-functional team of ~80 across product, engineering, design and data — with delivery recognised at COO level. That includes the bank's first automated SME decisioning workflow and a GenAI financial-spreading product.",
    tags: ['Financial Services', 'GenAI', 'Enterprise', '80-person team'],
    panelVariant: 'ink',
    panelLabel: 'New lending · Month one',
    dominant: '£5.8',
    dominantEm: 'M',
    dominantCaption:
      'generated by the first automated SME decisioning workflow at Lloyds, in its first month live.',
    secondary: [
      { value: '~80', label: 'Person team, COO-visible' },
      { value: '−40%', label: 'Time to credit decision' },
    ],
  },
  {
    slug: 'wagamama',
    index: '02',
    company: 'Wagamama · Loyalty & App',
    period: '',
    titleLead: 'A loyalty app that hit',
    titleEm: '№1 on iOS at launch.',
    description:
      'I led a cross-functional team of 30+ from inception through strategy, build and launch of a consumer loyalty proposition and mobile app — owning discovery, proposition design and the loyalty mechanic itself, including a web-wrapped payment flow.',
    tags: ['Consumer', 'Loyalty', 'iOS / Android', 'CRO'],
    panelVariant: 'moss',
    panelLabel: 'Signups · First 9 months',
    dominant: '1',
    dominantEm: 'M',
    dominantCaption:
      'people signed up — and ranked №1 iOS app in Food & Drink at launch.',
    secondary: [
      { value: '№1', label: 'iOS Food & Drink' },
      { value: '+58%', label: 'Visit frequency, post-launch' },
    ],
  },
  {
    slug: 'hca-healthcare',
    index: '03',
    company: 'HCA Healthcare · Primary Care',
    period: '',
    titleLead: 'Zero to one on',
    titleEm: "private healthcare's digital front door.",
    description:
      'I ran end-to-end patient discovery, researching directly with patients to identify acquisition funnel pain-points and shape a refined primary care proposition — then owned the full roadmap from zero to one across web and native app, expanding into corporate markets.',
    tags: ['Healthcare', 'Zero-to-one', 'Native + Web', 'B2B expansion'],
    panelVariant: 'peach',
    panelLabel: 'B2C growth · Year one',
    dominant: '+30',
    dominantEm: '%',
    dominantCaption:
      'growth in year one, then expanded into corporate healthcare markets.',
    secondary: [
      { value: '0→1', label: 'Web + native, from scratch' },
      { value: '2', label: 'Markets: self-pay + corporate' },
    ],
  },
]

export function getCaseStudy(slug: string): CaseStudy | undefined {
  return caseStudies.find((cs) => cs.slug === slug)
}
